### PR TITLE
[#142854167] Update from upstream

### PR DESCRIPTION
**Pull request by henrytk**
## What

[#142854167](https://www.pivotaltracker.com/story/show/142854167)

We want to fix a bug whereby the nozzle is not processing URIs that have the scheme (http://) at the start. Upstream has already fixed this issue, so we have fast-forwarded master and can now merge that into our gds_master to use the updated version.

## How to review

I have a temporary commit on branch `upgrade-graphite-nozzle` of paas-cf, which could be used to deploy and test using the version of the app on the master branch. I deployed it and all of the tests passed. It is up to the reviewer whether they feel a deploy is necessary.

## Who

Anyone but me

### CODE REVIEW

**Comment by combor** [comment]
I really don't like that inexplicit return here: https://github.com/alphagov/paas-graphite-nozzle/pull/5/files#diff-08ce7606ed14f570fd737f434dc9494cR41 but I can see that uri parsing is fixed here: https://github.com/alphagov/paas-graphite-nozzle/pull/5/files#diff-08ce7606ed14f570fd737f434dc9494cR47
and tests are adjusted as well: https://github.com/alphagov/paas-graphite-nozzle/pull/5/files#diff-0f983df2452e34a2682aa960d180f69bR30

I'm going to merge this.

**Comment by henrytk** [comment]
@combor I think the 'naked' return is Golang's least liked feature. I'm not sure how I feel about it.

**Comment by alext** [comment]
> combor deleted the `master` branch 17 hours ago

Did you mean to do that?

**Comment by henrytk** [comment]
I wonder if the deletion was due to use of the `merge_pr` make target. It could do with a `--do-not-delete` flag or something.

**Pull request merged**
